name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SBCL and ocicl
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install sbcl ocicl
          ocicl setup >> ~/.sbclrc

      - name: Install dependencies
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          ocicl install

      - name: Run linter
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          ocicl lint src/ tests/

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SBCL and ocicl
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install sbcl ocicl
          ocicl setup >> ~/.sbclrc

      - name: Install dependencies
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          ocicl install

      - name: Run tests
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          sbcl --noinform --non-interactive \
            --eval '(asdf:test-system :llog)' \
            --eval '(asdf:test-system :llog/audit)' \
            2>&1 | tee test-output.txt

      - name: Check test results
        run: |
          if grep -q "Fail: 0" test-output.txt && grep -q "Pass:" test-output.txt; then
            echo "✅ All tests passed!"
            exit 0
          else
            echo "❌ Tests failed!"
            exit 1
          fi

      - name: Display test summary
        if: always()
        run: |
          echo "=== Test Summary ==="
          grep "Did.*checks" test-output.txt || true
          grep -A 1 "Pass:" test-output.txt || true
